### ISSUE TITLE
giao！

### ISSUE THREAD

**Issue by Fuwaki** [SlimeNull/NullLib.VirtualForms#1]
好小伙子，敢乱close老子的issues
有问题还不解决
你这叫做逃避
(理直气壮)
哼唧！！！！ @SlimeNull 

https://user-images.githubusercontent.com/52279718/130462130-d572f565-b2b9-47f0-b67e-0eb45228e954.mp4

**Comment by EnderMo** [comment]
天呐,fly,你把GitHub弄臭了,说不定诺尔被你臭晕了呢

**Comment by SlimeNull** [comment]
先辈的呐喊, 革命者的冲锋号! (手动滑稽

**Comment by IamRuaRua** [comment]
🐮🐎fly

**Comment by EnderMo** [comment]
> 🐮🐎fly

好样的fly(翻译(确信

**Comment by IamRuaRua** [comment]
> > 🐮🐎fly
> 
> 好样的fly(翻译(确信

怎么改名字☹️

**Comment by EnderMo** [comment]
> > > 🐮🐎fly
> > 
> > 
> > 好样的fly(翻译(确信
> 
> 怎么改名字☹️

Edit profile

**Comment by SlimeNull** [comment]
好家伙，聊起来了居然！

**Comment by EnderMo** [comment]
来了

**Comment by Fuwaki** [comment]
离谱

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Fuwaki** [comment]
牛马

**Comment by SlimeNull** [comment]
草, 隐藏的秘密留言框

**Comment by EnderMo** [comment]
宝藏(
